# Generated by Django 4.1.5 on 2023-01-30 15:23

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(max_length=100)),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(max_length=100)),
                ('course_taken_in_year', models.IntegerField()),
                ('about', models.TextField(blank=True)),
                ('reviews', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.course')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor_post_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('content', models.TextField(blank=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor_post_pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ImageField(blank=True, upload_to='')),
                ('url', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('pdf_link', models.CharField(blank=True, max_length=1000)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Course_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_link_drive', models.CharField(blank=True, max_length=1000)),
                ('youtube_Resources', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('youtube_Title', models.CharField(blank=True, max_length=200)),
                ('youtube_Body', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.semester'),
        ),
    ]
