# Generated by Django 4.1.5 on 2023-01-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_url_branch_branch_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='branch_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='instructor_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='instructor_post_pdf',
            old_name='instructor_post_pdf_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='instructor_post_text',
            old_name='instructor_post_text_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='semester_url',
            new_name='url',
        ),
    ]
