# Generated by Django 4.1.5 on 2023-01-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_postforimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postforimage',
            name='pdf_link',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
