# Generated by Django 4.1.5 on 2023-01-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_branch_url_branch_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor_post_pdf',
            name='title',
            field=models.CharField(blank=True, max_length=644),
        ),
    ]
