# Generated by Django 4.1.5 on 2023-01-27 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_postforimage_pdf_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='college',
        ),
        migrations.DeleteModel(
            name='College',
        ),
    ]
