# Generated by Django 4.1.5 on 2023-02-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_instructor_post_pdf_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor_post_pdf',
            name='content',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='instructor_post_pdf',
            name='title',
            field=models.CharField(blank=True, max_length=144),
        ),
        migrations.AlterField(
            model_name='instructor_post_text',
            name='image',
            field=models.ImageField(blank=True, upload_to='image_for_post/'),
        ),
    ]
