# Generated by Django 4.1.5 on 2023-01-30 12:39

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_branch_college_delete_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_link_drive', models.CharField(blank=True, max_length=1000)),
                ('youtube_Resources', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('youtube_Title', models.CharField(blank=True, max_length=200)),
                ('youtube_Body', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.course')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor_post_pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ImageField(blank=True, upload_to='')),
                ('content', models.TextField(blank=True)),
                ('pdf_link', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor_post_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='books_drive_link',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='content',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='youtube_embed_videos',
        ),
        migrations.DeleteModel(
            name='PostForImage',
        ),
        migrations.AddField(
            model_name='instructor_post_text',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.instructor'),
        ),
        migrations.AddField(
            model_name='instructor_post_pdf',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.instructor'),
        ),
    ]
