# Generated by Django 4.1.5 on 2023-02-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('branch', models.CharField(choices=[('ECE', 'ECE'), ('CSE', 'CSE'), ('Chemical', 'Chemical'), ('Mining', 'Mining'), ('IT', 'IT'), ('Mech', 'Mech')], max_length=100)),
                ('semester', models.IntegerField(max_length=8)),
                ('about', models.TextField(max_length=244)),
            ],
        ),
    ]
