# Generated by Django 4.1.5 on 2023-02-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(blank=True, choices=[('ECE', 'ECE'), ('CSE', 'CSE'), ('Chemical', 'Chemical'), ('Mining', 'Mining'), ('IT', 'IT'), ('Mech', 'Mech')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
